# Ordered from oldest/stablest to newest.
base_branch: "bb-10.6-release"

branches:
  - "bb-10.6-release"
  - "bb-10.11-release"
  - "bb-11.4-release"
  - "bb-11.8-release"

notifications:
  slack:
    enabled: true
    secret: SLACK_WEBHOOK_URL
  zulip:
    enabled: true
    secret: ZULIP_WEBHOOK_URL
