name: Test forward merge check

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          python3 -m unittest discover \
            -s .github/forward-merge-check/tests
