name: Test cache

on:
    workflow_dispatch:

jobs:
    test-cache:
        runs-on: ubuntu-latest
        permissions:
          actions: write
        steps:

        - uses: actions/cache/restore@v5
          id: cache_restore
          with:
           path: random.txt
           key: cache_random_number

        - name: Display restored random number
          run: cat random.txt || echo "No cache found, generating new random number."
        - name: Write random number to file
          run: echo $RANDOM > random.txt

        - name: Display current random number
          run: cat random.txt

        - name: Delete cache key using gh cli
          run: gh cache delete cache_random_number || echo "Cache key not found, nothing to delete."

          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_REPO: ${{ github.repository }}
            BRANCH: ${{ github.ref_name }}

        - uses: actions/cache/save@v5
          id: cache_save
          with:
           path: random.txt
           key: cache_random_number

